queue.mem.events: 4096
max_procs: 4

apm-server:
  name: "apm-server"
  host: "0.0.0.0:8200"
  rum:
    enabled: true  

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "elastic"
  password: "changeme"