ARG ELK_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/apm/apm-server:${ELK_VERSION}

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
